name: roggle
description: Simple, colorful and easy to expand logger for dart. Inspired by the logger and dependent to the logger.

version: 0.2.1+1
homepage: https://github.com/susatthi/roggle

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  logger: ^1.1.0
  meta: ">=1.7.0"
  stack_trace: ">=1.10.0"

dev_dependencies:
  coverage: <2.0.0
  pedantic_mono: ^1.20.0
  test: ^1.21.6
